"use client";
import { Flex } from "@mantine/core";

import { MainTable } from "@/components/MainTable/MainTable";

export default function AccountsIIS(): JSX.Element {
  const data = {
    columns: [
      "ID",
      "Name",
      "Age",
      "City",
      "Country",
      "Email",
      "Phone",
      "Occupation",
      "Company",
      "Salary",
      "JoinDate",
      "Status",
      "Gender",
      "Hobby",
      "Education",
      "Experience",
      "Language",
      "Skill1",
      "Skill2",
      "Skill3",
      "Skill4",
      "Skill5",
      "Project1",
      "Project2",
      "Project3",
      "Rating",
      "Feedback",
      "Address",
      "ZipCode",
      "State",
      "Website",
      "SocialMedia",
      "Notes",
      "LastLogin",
      "ProfilePicture",
      "Bio",
      "FavoriteColor",
      "PetName",
    ],
    data: [
      {
        ID: 1,
        Name: "AliceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeAliceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
        Age: 30,
        City: "New York",
        Country: "USA",
        Email: "alice@example.com",
        Phone: "123-456-7890",
        Occupation: "Engineer",
        Company: "Tech Co",
        Salary: 70_000,
        JoinDate: "2020-01-15",
        Status: "Active",
        Gender: "Female",
        Hobby: "Reading",
        Education: "Bachelor's",
        Experience: 5,
        Language: "English",
        Skill1: "JavaScript",
        Skill2: "React",
        Skill3: "Node.js",
        Skill4: "CSS",
        Skill5: "HTML",
        Project1: "Project A",
        Project2: "Project B",
        Project3: "Project C",
        Rating: 4.5,
        Feedback: "Great team player",
        Address: "123 Main St",
        ZipCode: "10001",
        State: "NY",
        Website: "alice.com",
        SocialMedia: "@alice",
        Notes: "N/A",
        LastLogin: "2023-10-01",
        ProfilePicture: "url_to_picture",
        Bio: "Software engineer with a passion for technology.",
        FavoriteColor: "Blue",
        PetName: "Buddy",
      },
      {
        ID: 1,
        Name: "Alice",
        Age: 30,
        City: "New York",
        Country: "USA",
        Email: "alice@example.com",
        Phone: "123-456-7890",
        Occupation: "Engineer",
        Company: "Tech Co",
        Salary: 70_000,
        JoinDate: "2020-01-15",
        Status: "Active",
        Gender: "Female",
        Hobby: "Reading",
        Education: "Bachelor's",
        Experience: 5,
        Language: "English",
        Skill1: "JavaScript",
        Skill2: "React",
        Skill3: "Node.js",
        Skill4: "CSS",
        Skill5: "HTML",
        Project1: "Project A",
        Project2: "Project B",
        Project3: "Project C",
        Rating: 4.5,
        Feedback: "Great team player",
        Address: "123 Main St",
        ZipCode: "10001",
        State: "NY",
        Website: "alice.com",
        SocialMedia: "@alice",
        Notes: "N/A",
        LastLogin: "2023-10-01",
        ProfilePicture: "url_to_picture",
        Bio: "Software engineer with a passion for technology.",
        FavoriteColor: "Blue",
        PetName: "Buddy",
      },
      {
        ID: 1,
        Name: "Alice",
        Age: 30,
        City: "New York",
        Country: "USA",
        Email: "alice@example.com",
        Phone: "123-456-7890",
        Occupation: "Engineer",
        Company: "Tech Co",
        Salary: 70_000,
        JoinDate: "2020-01-15",
        Status: "Active",
        Gender: "Female",
        Hobby: "Reading",
        Education: "Bachelor's",
        Experience: 5,
        Language: "English",
        Skill1: "JavaScript",
        Skill2: "React",
        Skill3: "Node.js",
        Skill4: "CSS",
        Skill5: "HTML",
        Project1: "Project A",
        Project2: "Project B",
        Project3: "Project C",
        Rating: 4.5,
        Feedback: "Great team player",
        Address: "123 Main St",
        ZipCode: "10001",
        State: "NY",
        Website: "alice.com",
        SocialMedia: "@alice",
        Notes: "N/A",
        LastLogin: "2023-10-01",
        ProfilePicture: "url_to_picture",
        Bio: "Software engineer with a passion for technology.",
        FavoriteColor: "Blue",
        PetName: "Buddy",
      },
      {
        ID: 1,
        Name: "Alice",
        Age: 30,
        City: "New York",
        Country: "USA",
        Email: "alice@example.com",
        Phone: "123-456-7890",
        Occupation: "Engineer",
        Company: "Tech Co",
        Salary: 70_000,
        JoinDate: "2020-01-15",
        Status: "Active",
        Gender: "Female",
        Hobby: "Reading",
        Education: "Bachelor's",
        Experience: 5,
        Language: "English",
        Skill1: "JavaScript",
        Skill2: "React",
        Skill3: "Node.js",
        Skill4: "CSS",
        Skill5: "HTML",
        Project1: "Project A",
        Project2: "Project B",
        Project3: "Project C",
        Rating: 4.5,
        Feedback: "Great team player",
        Address: "123 Main St",
        ZipCode: "10001",
        State: "NY",
        Website: "alice.com",
        SocialMedia: "@alice",
        Notes: "N/A",
        LastLogin: "2023-10-01",
        ProfilePicture: "url_to_picture",
        Bio: "Software engineer with a passion for technology.",
        FavoriteColor: "Blue",
        PetName: "Buddy",
      },
      {
        ID: 1,
        Name: "Alice",
        Age: 30,
        City: "New York",
        Country: "USA",
        Email: "alice@example.com",
        Phone: "123-456-7890",
        Occupation: "Engineer",
        Company: "Tech Co",
        Salary: 70_000,
        JoinDate: "2020-01-15",
        Status: "Active",
        Gender: "Female",
        Hobby: "Reading",
        Education: "Bachelor's",
        Experience: 5,
        Language: "English",
        Skill1: "JavaScript",
        Skill2: "React",
        Skill3: "Node.js",
        Skill4: "CSS",
        Skill5: "HTML",
        Project1: "Project A",
        Project2: "Project B",
        Project3: "Project C",
        Rating: 4.5,
        Feedback: "Great team player",
        Address: "123 Main St",
        ZipCode: "10001",
        State: "NY",
        Website: "alice.com",
        SocialMedia: "@alice",
        Notes: "N/A",
        LastLogin: "2023-10-01",
        ProfilePicture: "url_to_picture",
        Bio: "Software engineer with a passion for technology.",
        FavoriteColor: "Blue",
        PetName: "Buddy",
      },
      {
        ID: 1,
        Name: "Alice",
        Age: 30,
        City: "New York",
        Country: "USA",
        Email: "alice@example.com",
        Phone: "123-456-7890",
        Occupation: "Engineer",
        Company: "Tech Co",
        Salary: 70_000,
        JoinDate: "2020-01-15",
        Status: "Active",
        Gender: "Female",
        Hobby: "Reading",
        Education: "Bachelor's",
        Experience: 5,
        Language: "English",
        Skill1: "JavaScript",
        Skill2: "React",
        Skill3: "Node.js",
        Skill4: "CSS",
        Skill5: "HTML",
        Project1: "Project A",
        Project2: "Project B",
        Project3: "Project C",
        Rating: 4.5,
        Feedback: "Great team player",
        Address: "123 Main St",
        ZipCode: "10001",
        State: "NY",
        Website: "alice.com",
        SocialMedia: "@alice",
        Notes: "N/A",
        LastLogin: "2023-10-01",
        ProfilePicture: "url_to_picture",
        Bio: "Software engineer with a passion for technology.",
        FavoriteColor: "Blue",
        PetName: "Buddy",
      },
      {
        ID: 1,
        Name: "Alice",
        Age: 30,
        City: "New York",
        Country: "USA",
        Email: "alice@example.com",
        Phone: "123-456-7890",
        Occupation: "Engineer",
        Company: "Tech Co",
        Salary: 70_000,
        JoinDate: "2020-01-15",
        Status: "Active",
        Gender: "Female",
        Hobby: "Reading",
        Education: "Bachelor's",
        Experience: 5,
        Language: "English",
        Skill1: "JavaScript",
        Skill2: "React",
        Skill3: "Node.js",
        Skill4: "CSS",
        Skill5: "HTML",
        Project1: "Project A",
        Project2: "Project B",
        Project3: "Project C",
        Rating: 4.5,
        Feedback: "Great team player",
        Address: "123 Main St",
        ZipCode: "10001",
        State: "NY",
        Website: "alice.com",
        SocialMedia: "@alice",
        Notes: "N/A",
        LastLogin: "2023-10-01",
        ProfilePicture: "url_to_picture",
        Bio: "Software engineer with a passion for technology.",
        FavoriteColor: "Blue",
        PetName: "Buddy",
      },
      {
        ID: 1,
        Name: "Alice",
        Age: 30,
        City: "New York",
        Country: "USA",
        Email: "alice@example.com",
        Phone: "123-456-7890",
        Occupation: "Engineer",
        Company: "Tech Co",
        Salary: 70_000,
        JoinDate: "2020-01-15",
        Status: "Active",
        Gender: "Female",
        Hobby: "Reading",
        Education: "Bachelor's",
        Experience: 5,
        Language: "English",
        Skill1: "JavaScript",
        Skill2: "React",
        Skill3: "Node.js",
        Skill4: "CSS",
        Skill5: "HTML",
        Project1: "Project A",
        Project2: "Project B",
        Project3: "Project C",
        Rating: 4.5,
        Feedback: "Great team player",
        Address: "123 Main St",
        ZipCode: "10001",
        State: "NY",
        Website: "alice.com",
        SocialMedia: "@alice",
        Notes: "N/A",
        LastLogin: "2023-10-01",
        ProfilePicture: "url_to_picture",
        Bio: "Software engineer with a passion for technology.",
        FavoriteColor: "Blue",
        PetName: "Buddy",
      },
      {
        ID: 1,
        Name: "Alice",
        Age: 30,
        City: "New York",
        Country: "USA",
        Email: "alice@example.com",
        Phone: "123-456-7890",
        Occupation: "Engineer",
        Company: "Tech Co",
        Salary: 70_000,
        JoinDate: "2020-01-15",
        Status: "Active",
        Gender: "Female",
        Hobby: "Reading",
        Education: "Bachelor's",
        Experience: 5,
        Language: "English",
        Skill1: "JavaScript",
        Skill2: "React",
        Skill3: "Node.js",
        Skill4: "CSS",
        Skill5: "HTML",
        Project1: "Project A",
        Project2: "Project B",
        Project3: "Project C",
        Rating: 4.5,
        Feedback: "Great team player",
        Address: "123 Main St",
        ZipCode: "10001",
        State: "NY",
        Website: "alice.com",
        SocialMedia: "@alice",
        Notes: "N/A",
        LastLogin: "2023-10-01",
        ProfilePicture: "url_to_picture",
        Bio: "Software engineer with a passion for technology.",
        FavoriteColor: "Blue",
        PetName: "Buddy",
      },
      {
        ID: 1,
        Name: "Alice",
        Age: 30,
        City: "New York",
        Country: "USA",
        Email: "alice@example.com",
        Phone: "123-456-7890",
        Occupation: "Engineer",
        Company: "Tech Co",
        Salary: 70_000,
        JoinDate: "2020-01-15",
        Status: "Active",
        Gender: "Female",
        Hobby: "Reading",
        Education: "Bachelor's",
        Experience: 5,
        Language: "English",
        Skill1: "JavaScript",
        Skill2: "React",
        Skill3: "Node.js",
        Skill4: "CSS",
        Skill5: "HTML",
        Project1: "Project A",
        Project2: "Project B",
        Project3: "Project C",
        Rating: 4.5,
        Feedback: "Great team player",
        Address: "123 Main St",
        ZipCode: "10001",
        State: "NY",
        Website: "alice.com",
        SocialMedia: "@alice",
        Notes: "N/A",
        LastLogin: "2023-10-01",
        ProfilePicture: "url_to_picture",
        Bio: "Software engineer with a passion for technology.",
        FavoriteColor: "Blue",
        PetName: "Buddy",
      },
      {
        ID: 1,
        Name: "Alice",
        Age: 30,
        City: "New York",
        Country: "USA",
        Email: "alice@example.com",
        Phone: "123-456-7890",
        Occupation: "Engineer",
        Company: "Tech Co",
        Salary: 70_000,
        JoinDate: "2020-01-15",
        Status: "Active",
        Gender: "Female",
        Hobby: "Reading",
        Education: "Bachelor's",
        Experience: 5,
        Language: "English",
        Skill1: "JavaScript",
        Skill2: "React",
        Skill3: "Node.js",
        Skill4: "CSS",
        Skill5: "HTML",
        Project1: "Project A",
        Project2: "Project B",
        Project3: "Project C",
        Rating: 4.5,
        Feedback: "Great team player",
        Address: "123 Main St",
        ZipCode: "10001",
        State: "NY",
        Website: "alice.com",
        SocialMedia: "@alice",
        Notes: "N/A",
        LastLogin: "2023-10-01",
        ProfilePicture: "url_to_picture",
        Bio: "Software engineer with a passion for technology.",
        FavoriteColor: "Blue",
        PetName: "Buddy",
      },
      {
        ID: 1,
        Name: "Alice",
        Age: 30,
        City: "New York",
        Country: "USA",
        Email: "alice@example.com",
        Phone: "123-456-7890",
        Occupation: "Engineer",
        Company: "Tech Co",
        Salary: 70_000,
        JoinDate: "2020-01-15",
        Status: "Active",
        Gender: "Female",
        Hobby: "Reading",
        Education: "Bachelor's",
        Experience: 5,
        Language: "English",
        Skill1: "JavaScript",
        Skill2: "React",
        Skill3: "Node.js",
        Skill4: "CSS",
        Skill5: "HTML",
        Project1: "Project A",
        Project2: "Project B",
        Project3: "Project C",
        Rating: 4.5,
        Feedback: "Great team player",
        Address: "123 Main St",
        ZipCode: "10001",
        State: "NY",
        Website: "alice.com",
        SocialMedia: "@alice",
        Notes: "N/A",
        LastLogin: "2023-10-01",
        ProfilePicture: "url_to_picture",
        Bio: "Software engineer with a passion for technology.",
        FavoriteColor: "Blue",
        PetName: "Buddy",
      },
      {
        ID: 1,
        Name: "Alice",
        Age: 30,
        City: "New York",
        Country: "USA",
        Email: "alice@example.com",
        Phone: "123-456-7890",
        Occupation: "Engineer",
        Company: "Tech Co",
        Salary: 70_000,
        JoinDate: "2020-01-15",
        Status: "Active",
        Gender: "Female",
        Hobby: "Reading",
        Education: "Bachelor's",
        Experience: 5,
        Language: "English",
        Skill1: "JavaScript",
        Skill2: "React",
        Skill3: "Node.js",
        Skill4: "CSS",
        Skill5: "HTML",
        Project1: "Project A",
        Project2: "Project B",
        Project3: "Project C",
        Rating: 4.5,
        Feedback: "Great team player",
        Address: "123 Main St",
        ZipCode: "10001",
        State: "NY",
        Website: "alice.com",
        SocialMedia: "@alice",
        Notes: "N/A",
        LastLogin: "2023-10-01",
        ProfilePicture: "url_to_picture",
        Bio: "Software engineer with a passion for technology.",
        FavoriteColor: "Blue",
        PetName: "Buddy",
      },
      {
        ID: 1,
        Name: "Alice",
        Age: 30,
        City: "New York",
        Country: "USA",
        Email: "alice@example.com",
        Phone: "123-456-7890",
        Occupation: "Engineer",
        Company: "Tech Co",
        Salary: 70_000,
        JoinDate: "2020-01-15",
        Status: "Active",
        Gender: "Female",
        Hobby: "Reading",
        Education: "Bachelor's",
        Experience: 5,
        Language: "English",
        Skill1: "JavaScript",
        Skill2: "React",
        Skill3: "Node.js",
        Skill4: "CSS",
        Skill5: "HTML",
        Project1: "Project A",
        Project2: "Project B",
        Project3: "Project C",
        Rating: 4.5,
        Feedback: "Great team player",
        Address: "123 Main St",
        ZipCode: "10001",
        State: "NY",
        Website: "alice.com",
        SocialMedia: "@alice",
        Notes: "N/A",
        LastLogin: "2023-10-01",
        ProfilePicture: "url_to_picture",
        Bio: "Software engineer with a passion for technology.",
        FavoriteColor: "Blue",
        PetName: "Buddy",
      },
      {
        ID: 1,
        Name: "Alice",
        Age: 30,
        City: "New York",
        Country: "USA",
        Email: "alice@example.com",
        Phone: "123-456-7890",
        Occupation: "Engineer",
        Company: "Tech Co",
        Salary: 70_000,
        JoinDate: "2020-01-15",
        Status: "Active",
        Gender: "Female",
        Hobby: "Reading",
        Education: "Bachelor's",
        Experience: 5,
        Language: "English",
        Skill1: "JavaScript",
        Skill2: "React",
        Skill3: "Node.js",
        Skill4: "CSS",
        Skill5: "HTML",
        Project1: "Project A",
        Project2: "Project B",
        Project3: "Project C",
        Rating: 4.5,
        Feedback: "Great team player",
        Address: "123 Main St",
        ZipCode: "10001",
        State: "NY",
        Website: "alice.com",
        SocialMedia: "@alice",
        Notes: "N/A",
        LastLogin: "2023-10-01",
        ProfilePicture: "url_to_picture",
        Bio: "Software engineer with a passion for technology.",
        FavoriteColor: "Blue",
        PetName: "Buddy",
      },
      {
        ID: 1,
        Name: "Alice",
        Age: 30,
        City: "New York",
        Country: "USA",
        Email: "alice@example.com",
        Phone: "123-456-7890",
        Occupation: "Engineer",
        Company: "Tech Co",
        Salary: 70_000,
        JoinDate: "2020-01-15",
        Status: "Active",
        Gender: "Female",
        Hobby: "Reading",
        Education: "Bachelor's",
        Experience: 5,
        Language: "English",
        Skill1: "JavaScript",
        Skill2: "React",
        Skill3: "Node.js",
        Skill4: "CSS",
        Skill5: "HTML",
        Project1: "Project A",
        Project2: "Project B",
        Project3: "Project C",
        Rating: 4.5,
        Feedback: "Great team player",
        Address: "123 Main St",
        ZipCode: "10001",
        State: "NY",
        Website: "alice.com",
        SocialMedia: "@alice",
        Notes: "N/A",
        LastLogin: "2023-10-01",
        ProfilePicture: "url_to_picture",
        Bio: "Software engineer with a passion for technology.",
        FavoriteColor: "Blue",
        PetName: "Buddy",
      },
      {
        ID: 1,
        Name: "Alice",
        Age: 30,
        City: "New York",
        Country: "USA",
        Email: "alice@example.com",
        Phone: "123-456-7890",
        Occupation: "Engineer",
        Company: "Tech Co",
        Salary: 70_000,
        JoinDate: "2020-01-15",
        Status: "Active",
        Gender: "Female",
        Hobby: "Reading",
        Education: "Bachelor's",
        Experience: 5,
        Language: "English",
        Skill1: "JavaScript",
        Skill2: "React",
        Skill3: "Node.js",
        Skill4: "CSS",
        Skill5: "HTML",
        Project1: "Project A",
        Project2: "Project B",
        Project3: "Project C",
        Rating: 4.5,
        Feedback: "Great team player",
        Address: "123 Main St",
        ZipCode: "10001",
        State: "NY",
        Website: "alice.com",
        SocialMedia: "@alice",
        Notes: "N/A",
        LastLogin: "2023-10-01",
        ProfilePicture: "url_to_picture",
        Bio: "Software engineer with a passion for technology.",
        FavoriteColor: "Blue",
        PetName: "Buddy",
      },
      {
        ID: 1,
        Name: "Alice",
        Age: 30,
        City: "New York",
        Country: "USA",
        Email: "alice@example.com",
        Phone: "123-456-7890",
        Occupation: "Engineer",
        Company: "Tech Co",
        Salary: 70_000,
        JoinDate: "2020-01-15",
        Status: "Active",
        Gender: "Female",
        Hobby: "Reading",
        Education: "Bachelor's",
        Experience: 5,
        Language: "English",
        Skill1: "JavaScript",
        Skill2: "React",
        Skill3: "Node.js",
        Skill4: "CSS",
        Skill5: "HTML",
        Project1: "Project A",
        Project2: "Project B",
        Project3: "Project C",
        Rating: 4.5,
        Feedback: "Great team player",
        Address: "123 Main St",
        ZipCode: "10001",
        State: "NY",
        Website: "alice.com",
        SocialMedia: "@alice",
        Notes: "N/A",
        LastLogin: "2023-10-01",
        ProfilePicture: "url_to_picture",
        Bio: "Software engineer with a passion for technology.",
        FavoriteColor: "Blue",
        PetName: "Buddy",
      },
    ],
  };

  return (
    <>
      <Flex
        direction="column"
        p={0}
        gap={0}
        w="100%"
        h="100%"
        style={{ overflow: "hidden" }}
      >
        <MainTable data={data.data} columns={data.columns} isEdit={true} />
      </Flex>
    </>
  );
}
